In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
from sklearn.datasets import make_classification

In [27]:
## create the dataset
X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=15)

In [28]:
# standardized values - no need to do standardization because currently i am focusing on implementation only
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -0.377957  1.043895  1.043494 -0.101838 -1.617442  0.402713  0.913601   
1   -0.325259  1.276263 -0.686123 -2.463205 -0.489426 -0.240715 -1.469496   
2    0.739019 -0.600903 -0.177294  1.335714 -0.817332 -0.790047  1.457365   
3    0.474312 -1.103002  1.189936 -0.800186  0.912377 -0.406451 -1.130950   
4    0.927365  1.114796  0.080284  1.261064  0.761179  0.921563  0.440832   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.538272  0.171629  0.075371 -0.957658 -1.066219  1.158096 -0.036964   
996 -0.060266  0.095018 -0.271685  1.830560  0.219445 -0.341269  1.180088   
997  0.675563 -0.538420 -1.299500  0.747835  1.733898 -0.268044 -0.520953   
998  2.629710 -2.452899 -1.359785  1.592065  0.854157  1.618828  0.621701   
999 -1.791491 -0.121908  0.535153 -0.588085 -1.929461 -0.659900  0.754921   

            7         8         9  
0   -0.067192  0.175471 -1.049646  
1    1.006633 -0.833692  0.957744  
2   -0.218981  0.878643 -1.257740  
3    1.985111  1.379029  1.041768  
4    0.184645 -1.567739 -0.142107  
..        ...       ...       ...  
995  0.123689  0.927871 -0.225003  
996 -0.216876 -1.752938 -0.810152  
997  2.043336  0.947388  0.790354  
998  0.378898 -1.971894 -0.252250  
999 -1.941357  0.589002 -1.007482  

[1000 rows x 10 columns]

In [29]:
y

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.30, random_state=42)

In [31]:
# import model  
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

# model train 
logistic.fit(X_train,y_train)

# do prediction on test data
y_pred=logistic.predict(X_test)
print(y_pred)

[0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1
 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1
 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 1
 0 0 1 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 0 0]


In [32]:
# check performance matrices
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [33]:
score=accuracy_score(y_pred,y_test)
print("socre is ", score)

print(classification_report(y_pred,y_test))

print("Confusion matrix is ")
print(confusion_matrix(y_pred,y_test))

socre is  0.9166666666666666
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       160
           1       0.90      0.92      0.91       140

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion matrix is 
[[146  14]
 [ 11 129]]


# Hyperparameter Tunning and Cross Validation 

## Grid SearchCv

In [43]:
param_grid = [
    {
        'solver': ['liblinear'],
        'penalty': ['l1', 'l2'],
        'C': [100, 10, 1.0, 0.1, 0.01]
    },
    {
        'solver': ['lbfgs', 'newton-cg', 'sag'],
        'penalty': ['l2'],
        'C': [100, 10, 1.0, 0.1, 0.01]
    },
    {
        'solver': ['saga'],
        'penalty': ['l1', 'l2', 'elasticnet'],
        'C': [100, 10, 1.0, 0.1, 0.01],
        'l1_ratio': [0.5]  # required for elasticnet
    }
]


## C Value in Machine Learning (Logistic Regression / SVM)

The **C value** is a **regularization parameter** used in models like **Logistic Regression** and **Support Vector Machines (SVM)**.

### Meaning of C
- **C controls the trade-off** between:
  - fitting the training data well  
  - keeping the model simple (regularized)

It is the **inverse of regularization strength**.

### Effect of C Value
- **Small C (e.g., 0.01, 0.1)**  
  → Strong regularization  
  → Simpler model  
  → May underfit  

- **Large C (e.g., 10, 100)**  
  → Weak regularization  
  → More complex model  
  → May overfit  

### Why C is Tuned in GridSearchCV
Different C values can significantly change model performance.  
GridSearchCV tests multiple C values to find the best balance between **bias and variance**.

### One-Line Definition
**C is a regularization parameter that controls how strictly a model fits the training data.**


## Solvers in GridSearchCV

In GridSearchCV, a **solver** is not a component of GridSearchCV itself, but a **hyperparameter of the machine learning model**. It defines the **optimization algorithm** used to minimize the loss function and learn the model parameters.

### Role of Solvers
Solvers control how efficiently and accurately a model is trained. The choice of solver affects:
- Training speed  
- Convergence behavior  
- Type of regularization supported  
- Suitability for small or large datasets  

### Example: Logistic Regression Solvers
- **liblinear** – Suitable for small datasets; supports L1 and L2 regularization  
- **lbfgs** – Efficient and commonly used; supports multiclass classification  
- **newton-cg** – Uses second-order optimization; good for larger datasets  
- **sag** – Fast for large datasets; requires feature scaling  
- **saga** – Supports L1, L2, and ElasticNet regularization; scalable  

### Use in GridSearchCV
GridSearchCV evaluates different solvers by treating them as hyperparameters and selects the solver that yields the best performance based on the chosen scoring metric.

### Summary
Choosing the right solver helps achieve faster convergence, better accuracy, and stable model training.


In [44]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

## Stratified K-Fold Cross-Validation

Stratified K-Fold Cross-Validation is used mainly for **classification problems**.  
It splits the data into K folds such that **each fold maintains the same class distribution** as the original dataset.

This method is especially useful for **imbalanced datasets**, as it ensures that all classes are represented in every fold, leading to **more reliable and unbiased model evaluation**.


In [45]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV
model=LogisticRegression()
grid=GridSearchCV(estimator=model,param_grid=param_grid,scoring='accuracy',cv=cv,n_jobs=-1)

''' 
This line applies GridSearchCV to find the best hyperparameters for a given model.  
It tests all parameter combinations in `param_grid`, evaluates them using **accuracy**, applies 
**cross-validation (cv)**, and uses **all CPU cores** (`n_jobs = -1`) to speed up the process.
'''

' \nThis line applies GridSearchCV to find the best hyperparameters for a given model.  \nIt tests all parameter combinations in `param_grid`, evaluates them using **accuracy**, applies \n**cross-validation (cv)**, and uses **all CPU cores** (`n_jobs = -1`) to speed up the process.\n'

In [46]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['lbfgs', 'newton-cg', 'sag']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'solver': ['saga']}],
             scoring='accuracy')

In [47]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['lbfgs', 'newton-cg', 'sag']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'solver': ['saga']}],
             scoring='accuracy')

In [48]:
grid.best_params_

{'C': 0.01, 'l1_ratio': 0.5, 'penalty': 'elasticnet', 'solver': 'saga'}

In [49]:
grid.best_score_

np.float64(0.927142857142857)

In [50]:
y_pred=grid.predict(X_test)

In [ ]:
score=accuracy_score(y_pred,y_test)
print(score)

# classification report will pritn precesion, recall, and f1-score 
print(classification_report(y_pred,y_test))

# pritn confusion matrix
print(confusion_matrix(y_pred,y_test))

0.92
              precision    recall  f1-score   support

           0       0.95      0.90      0.93       165
           1       0.89      0.94      0.91       135

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[149  16]
 [  8 127]]


## Randomized SearchCV

In [52]:
from sklearn.model_selection import RandomizedSearchCV

In [55]:
param_dist = [
    {
        'solver': ['liblinear'],
        'penalty': ['l1', 'l2'],
        'C': [100, 10, 1.0, 0.1, 0.01]
    },
    {
        'solver': ['lbfgs', 'newton-cg', 'sag'],
        'penalty': ['l2'],
        'C': [100, 10, 1.0, 0.1, 0.01]
    },
    {
        'solver': ['saga'],
        'penalty': ['elasticnet'],
        'C': [100, 10, 1.0, 0.1, 0.01],
        'l1_ratio': [0.1, 0.5, 0.9]
    }
]

In [56]:
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model, param_distributions=param_dist, cv=5, scoring='accuracy')

In [57]:
randomcv.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions=[{'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l1', 'l2'],
                                         'solver': ['liblinear']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l2'],
                                         'solver': ['lbfgs', 'newton-cg',
                                                    'sag']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'l1_ratio': [0.1, 0.5, 0.9],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [58]:
randomcv.best_score_

np.float64(0.9214285714285714)

In [59]:
randomcv.best_params_

{'solver': 'liblinear', 'penalty': 'l1', 'C': 0.01}

In [60]:
y_pred=randomcv.predict(X_test)

In [ ]:
score=accuracy_score(y_pred,y_test)
print(score)

print(classification_report(y_pred,y_test))

print(confusion_matrix(y_pred,y_test))

0.9233333333333333
              precision    recall  f1-score   support

           0       0.97      0.89      0.93       170
           1       0.87      0.96      0.92       130

    accuracy                           0.92       300
   macro avg       0.92      0.93      0.92       300
weighted avg       0.93      0.92      0.92       300

[[152  18]
 [  5 125]]
